name: Build Snapshot 
description: Build (Snapshot) with Maven
inputs:
  pipeline-repo: 
    description: Repo level pipeline local yaml config file
    required: true
    default: ''
  pipeline_global: 
    description: Global level pipeline yaml config file
    required: true
    default: ''
  build_tools_settings: 
    description: Build Tool Settings
    required: false
    default: ''
  flags: 
    description: flags used during the buildd
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Building Snapshot with Maven
      shell: bash
      run: | 
            mvn --version
            mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress --settings ${{ github.workspace }}/global_configs/settings.xml
