name: Build Snapshot 
description: Build (Snapshot) with Maven
inputs:
  flags:  # id of input
    description: flags used during the buildd
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Building Snapshot with Maven
      shell: bash
      run: | 
            mvn --version
            mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress --settings ${{ github.workspace }}/global_configs/settings.xml
