name: Checkout Repo & Global Config
description: Checkout Repo & Global Config composite action

inputs:
  global_config_repo:
    description: The global config centralized repo
    required: false
    default: "theonlyfaddyinc/global_configs"
  global_config_repo_checkout_path:
    description: The global config repo checkout relative path
    required: false
    default: "global_configs"

# outputs:
#   pipeline_repo: 
#     description: The repo level pipeline YAML in json
#     value: ${{ steps.parser.outputs.pipeline_repo }}
#   pipeline_global: 
#     description: The global level pipeline YAML in json
#     value: ${{ steps.parser.outputs.pipeline_global }}

runs:
  using: "composite"
  steps:
    - id: checkout_current_repo
      name: Checkout current repo!
      uses: actions/checkout@v3
    - name: Clone global config repo - '${{ inputs.global_config_repo }}' under ''./${{ inputs.global_config_repo_checkout_path }}'
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.global_config_repo }}
        ref: main
        path: ${{ github.workspace }}/${{ inputs.global_config_repo_checkout_path }}


