name: Setup Build Tools
description: Setup the build tools with specific versions
inputs:
  jdk_version:  # id of input
    description: Version of JDK to be installed
    required: true
    default: '14'
  maven_version:
    description: Version of Maven to be installed
    required: true
    default: '3.6.3'
  pipeline_repo: 
    description: Config information at repo level in YAML
    required: true
  pipeline_global: 
    description: Config information at Global level in YAML
    required: true
    
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Identify built toolings set
      id: pre_reqs
      shell: bash
      run:  |
            
            # traverse the json for build information
            export BUILD_LANGS=$(echo '${{ inputs.pipeline_repo }}' | jq -r '.build.language | to_entries | map("build_lang_\(.key)=\(.value)") | @csv'  |  tr -d '"')
            export BUILD_TOOLS=$(echo '${{ inputs.pipeline_repo }}' | jq -r '.build.tool | to_entries | map("build_tools_\(.key)=\(.value)") | @csv'  |  tr -d '"')
            echo "BUILD_LANGS=$BUILD_LANGS"
            echo "BUILD_TOOLS=$BUILD_TOOLS"
            BUILD_TOOLS=$BUILD_TOOLS,$BUILD_LANGS
            echo "ALL BUILD  = $BUILD_TOOLS"
            IFS=',' read -ra ENV_VARS <<< "$BUILD_TOOLS"
            echo "ENV_VARS=$ENV_VARS"
            for i in "${ENV_VARS[@]}"; do
              echo "--------------------"
              echo $i
              echo $i >> $GITHUB_OUTPUT
            done
            echo "test_var=test_var" >> $GITHUB_OUTPUT
            echo "-------------------------"
            cat $GITHUB_OUTPUT

    # - run: echo Hello ${{ inputs.who-to-greet }}. From test-action-1
    #   shell: bash
    # - id: random-number-generator
    #   run: mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress --settings ${settings.config.build.tool.settingsPath} ${flags}
    #   shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # if {}
    - name: Test step
      shell: bash
      run:  |
            echo "Test Var = ${{ steps.pre_reqs.outputs.test_var }}"
            echo "build_lang_name = ${{ steps.pre_reqs.outputs.build_lang_name }}"
            echo "build_lang_version = ${{ steps.pre_reqs.outputs.build_lang_version }}"
            echo "build_tool_name = ${{ steps.pre_reqs.outputs.build_tools_name }}"
            echo "build_tool_version = ${{ steps.pre_reqs.outputs.build_tools_version }}"
            echo "build_tool_settings = ${{ steps.pre_reqs.outputs.build_tools_settings }}"
    - name: Set up JDK 14
      # if {{ }}
      # if: ${{ inputs.jdk_version }} == 14
      uses: theonlyfaddyinc/devops-standard-library/composite_actions/setup_build_tools/setup-jdk@main
      with:
        java-version:  ${{ inputs.jdk_version }}
        pipeline_repo: ${{ inputs.pipeline_repo }}
        pipeline_global: ${{ inputs.pipeline_global }}
    # else
    - name: Set up Maven
      uses: theonlyfaddyinc/devops-standard-library/composite_actions/setup_build_tools/setup-maven@main
      with:
        maven-version:  ${{ inputs.maven_version }}
        pipeline_repo: ${{ inputs.pipeline_repo }}
        pipeline_global: ${{ inputs.pipeline_global }}