name: Setup JDK & Maven 
description: Setup the build tools with specific versions
inputs:
  java-version:  # id of input
    description: Version of JDK to be installed
    required: true
    default: '14'
  pipeline_repo: 
    description: Config information at repo level in YAML
    required: true
  pipeline_global: 
    description: Config information at Global level in YAML
    required: true
    

runs:
  using: "composite"
  steps:
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version:  ${{ inputs.jdk_version }}
    - name: Check the JDK version
      shell: bash
      run: | 
            java --version