name: Build Snapshot 
description: Build Snapshot using respective build tool
inputs:
  build_lang_name:
    description: "Build Language"
    required: false
  build_tools_name:
    description: "Build Tool Name"
    required: false
  build_tools_settings:
    description: "Settings file defined in the local repo level"
    required: false
  pipeline_repo: 
    description: Config information at repo level in YAML
    required: true
  pipeline_global: 
    description: Config information at Global level in YAML
    required: true
  
    

runs:
  using: "composite"
  steps:
    - name:  Pre steps
      shell: bash
      run: echo pre steps
    - name: Build Release - Maven
      if: inputs.build_tools_name == 'maven'
      uses: theonlyfaddyinc/devops-standard-library/composite_actions/std_maven_actions/buildRelease@main
      with:
        pipeline-repo: ${{ inputs.pipeline_repo }}
        pipeline_global: ${{ inputs.pipeline_global }}
        build_tool_settings: $${{ inputs.build_tool_settings }}
        flags: ''
      # shell: bash
      # run:  |
      #       echo calling theonlyfaddyinc/devops-standard-library/composite_actions/std_maven_actions/buildSnapshot@main
    # - name: Build Snapshot - Pipeline
    #   if: $${{ inputs.build_tool_name }} == "pip"
    #   uses: ../std_pip_actions/build_snapshot