name: Build Snapshot 
description: Build Snapshot using respective build tool
inputs:
  build_lang_name:
    description: "Build Language"
    required: false
  build_tools_name:
    description: "Build Tool Name"
    required: false
  build_tools_settings:
    description: "Settings file defined in the local repo level"
    required: false
  pipeline_repo: 
    description: Config information at repo level in YAML
    required: true
  pipeline_global: 
    description: Config information at Global level in YAML
    required: true
  
    

runs:
  using: "composite"
  steps:
    - name:  Determine Pre & Post flags
      shell: bash
      run: |
            echo -e "\033[32;1m############ Determine Inputs ############"
            echo -e "\033[32;1m build_lang_name : ${{ inputs.build_lang_name }}"
            echo -e "\033[32;1m build_tools_name  : ${{ inputs.build_tools_name }}"
            echo -e "\033[32;1m build_tools_settings  : ${{ inputs.build_tools_settings }}"
            echo -e "\033[32;1m flags : "
            echo -e "\033[32;1m##########################################"

    - name: Build Snapshot - Maven
      if: inputs.build_tools_name == 'maven'
      uses: theonlyfaddyinc/devops-standard-library/composite_actions/std_maven_actions/buildSnapshot@main
      with:
        pipeline-repo: ${{ inputs.pipeline_repo }}
        pipeline_global: ${{ inputs.pipeline_global }}
        build_tool_settings: $${{ inputs.build_tools_settings }}
        flags: ''
      # shell: bash
      # run:  |
      #       echo calling theonlyfaddyinc/devops-standard-library/composite_actions/std_maven_actions/buildSnapshot@main
    # - name: Build Snapshot - Pipeline
    #   if: $${{ inputs.build_tool_name }} == "pip"
    #   uses: ../std_pip_actions/build_snapshot