name: Build Release 
description: Build Release Maven
inputs:
  flags:  # id of input
    description: flags used during the buildd
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: setup git config
      shell: bash
      run: |
        git config user.email "abinstephen@gmail.com"
        git config user.name "abinstephen"
        
    - name: Build Release with Maven
      shell: bash
      run: | 
            mvn --version
            mvn clean release:clean release:prepare release:perform -Dmaven.test.skip=true --batch-mode --update-snapshots ${{ github.workspace }}/global_configs/settings.xml

