name: Integration Snapshot Parent
run-name: ${{ github.ref_name }} | ${{ github.event_name }} | '${{ github.event.head_commit.message }}'

on: [workflow_dispatch, workflow_call]

jobs:
  BUILD_TEST_TEST_FUNC:
    name: Build Code | Run Unit Test | Run Functional Test
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout current repo!
    #   uses: actions/checkout@v3
    # - name: Clone global config repo under ./global_config
    #   uses: actions/checkout@v3
    #   with:
    #     repository: theonlyfaddyinc/global_configs
    #     ref: main
    #     path: ${{ github.workspace }}/global_configs
    # - name: Read YAML config files
    #   id: read_yaml
    #   uses: theonlyfaddyinc/devops-standard-library/composite_actions/parsers/read_repo_global_yaml@main
    #   with:
    #     local_config_path: pipeline.yaml
    #     global_config_path: global_configs/pipeline-global.yaml
    - name: Prepare - Checkout Repo(s) and Read YAML(s)
      id: pre_build
      uses: theonlyfaddyinc/devops-standard-library/composite_actions/prepare_phase/pre_build_steps@main
      with:
        global_config_repo: "theonlyfaddyinc/global_configs"
        global_config_repo_checkout_path: "global_configs"

    - name: Setup build tools & runtime installation
      id: setup_build_tools
      uses: theonlyfaddyinc/devops-standard-library/composite_actions/setup_build_tools@main
      with:
        pipeline_repo: ${{ steps.pre_build.outputs.pipeline_repo }}
        pipeline_global: ${{ steps.pre_build.outputs.pipeline_global }}

    - name: Build Snapshot
      run:  |
              echo "Maven call with settings file - ${{ steps.setup_build_tools.outputs.maven_settings_xml }}"
              mvn clean install -Dmaven.test.skip=true --update-snapshots --no-transfer-progress
  # Run_Unit_Tests:
  #   runs-on: ubuntu-latest
  #   needs: [Build_Code]
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - uses: theonlyfaddyinc/devops-standard-library/composite_action/setup-jdk-maven@main
  #     with:
  #       jdk_version: '14'
  #       maven_version: '3.8.1'

  #   - name: Test
  #     run: mvn test --update-snapshots --no-transfer-progress 
      
  # Run_Functional_Tests:
  #   runs-on: ubuntu-latest
  #   needs: [Run_Unit_Tests]
  #   steps:
  #   - uses: actions/checkout@v2

  #   - uses: theonlyfaddyinc/devops-standard-library/composite_action/setup-jdk-maven@main
  #     with:
  #       jdk_version: '14'
  #       maven_version: '3.8.1'

  #   - name: verify
  #     run: mvn verify --update-snapshots --no-transfer-progress     
      
  # Evaluate:
  #   runs-on: ubuntu-latest
  #   needs: [Run_Functional_Tests]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Check the JDK java-version
  #     run: | 
  #           java --version
  #           mvn --version      
  #   - name: evaluate
  #     run: mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout     
      
