name: "Pipeline Workflow Setup"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      sample_input:
        required: true
        type: string

  workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo!
        uses: actions/checkout@v3
      - name: Checkout devops repo under ./devops
        uses: actions/checkout@v3
        with:
          repository: theonlyfaddyinc/devops
          path: ./devops
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.sample_input }}
      - name: Run a multi-line script
        shell: sh
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. Got it ${{ inputs.sample_input }}?
          pwd
          ls -lta
          ls -lta devops/.github/workflows/
          cp devops/.github/workflows/*_pipeline.yml ./.github/workflows/
  step2:
    needs: step1
    name: Step 2
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple step
        run: echo "Run a simple step"
