name: Build Release 

on:
  workflow_call:
    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set git username and email
        run:
              |
              git config user.email "its.faddy@gmail.com"
              git config user.name "GITHUB_AUTO_AGENT"
              echo "Setting up of git username and email id completed!"
      - name: Run the maven release plugin
        shell: bash
        run: | 
              mvn --version
              mvn clean release:clean release:prepare release:perform -Dmaven.test.skip=true --batch-mode --update-snapshots ${{ github.workspace }}/global_configs/settings.xml
              


# GIT_COMMIT_TOKEN




# inputs:
#   flags:  # id of input
#     description: flags used during the buildd
#     required: true
#     default: ''

# runs:
#   using: "composite"
#   steps:
#     - name: setup git config
#       shell: bash
#       run: |
#         git config user.email "its.faddy@gmail.com"
#         git config user.name "GITHUB_AUTO_AGENT"
#         echo "Setting up of git username and email id completed!"
        
#     - name: Build Release with Maven
#       shell: bash
#       run: | 
#             mvn --version
#             mvn clean release:clean release:prepare release:perform -Dmaven.test.skip=true --batch-mode --update-snapshots ${{ github.workspace }}/global_configs/settings.xml

